<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="itrs_appserver.ThreadControllerTest" tests="6" skipped="0" failures="0" errors="0" timestamp="2016-02-11T14:12:52" hostname="ITRSLP043" time="0.451">
  <properties/>
  <testcase name="callWithNewThreadTest" classname="itrs_appserver.ThreadControllerTest" time="0.033"/>
  <testcase name="callWithAddTOExistingThreadTest" classname="itrs_appserver.ThreadControllerTest" time="0.131"/>
  <testcase name="removeUserFromNotifylistSingleUserTest" classname="itrs_appserver.ThreadControllerTest" time="0.048"/>
  <testcase name="restartNotfyListTest" classname="itrs_appserver.ThreadControllerTest" time="0.062"/>
  <testcase name="editDVTest" classname="itrs_appserver.ThreadControllerTest" time="0.084"/>
  <testcase name="removeUserFromNotifylistTwoUsersTest" classname="itrs_appserver.ThreadControllerTest" time="0.093"/>
  <system-out><![CDATA[14:12:52.644 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:21961]
[testa2]
14:12:52.645 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-13] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
14:12:52.666 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
This is the thread xpath : testa3
14:12:52.680 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-17] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:52.686 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:52.689 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  Remoting - Starting remoting
14:12:52.709 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:21981]
[testa3]
14:12:52.711 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
This is the thread xpath : testb3
14:12:52.775 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:52.779 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  Remoting - Starting remoting
14:12:52.792 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-11] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:22004]
[testb3]
14:12:52.794 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-10] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
14:12:52.813 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:52.817 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-8] INFO  Remoting - Starting remoting
14:12:52.834 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-10] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:22023]
[testb3, testc3]
14:12:52.838 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-10] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
This is the thread xpath : testf3
14:12:52.880 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
14:12:52.880 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-15] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
This is the thread xpath : testi3
14:12:52.897 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:52.900 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-19] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:52.900 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-11] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:52.902 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-7] INFO  Remoting - Starting remoting
14:12:52.932 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:52.938 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  Remoting - Starting remoting
This is the thread xpath : testd3
geneos_notification.objects.CustomDataView@2ffc9722
14:12:52.977 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-10] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:22069]
[testi3, testj3]
14:12:52.978 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
14:12:52.985 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-9] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
This is the thread xpath : teste3
14:12:53.015 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:53.019 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  Remoting - Starting remoting
14:12:53.026 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-14] INFO  c.itrsgroup.actor.MessageDispatcher - Successfully connected to remote service [akka.tcp://ClusterSystem@192.168.220.54:2551/user/frontEnd]
14:12:53.026 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-14] INFO  c.itrsgroup.actor.MessageDispatcher - Forwarding Subscription op to cluster frontend: Subscribe(ModelSub(testa2/rows/row[wild(@name,"*")]/cell,Set(),LIST,),None)
This is the thread xpath : testg3
14:12:53.067 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:53.071 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  Remoting - Starting remoting
14:12:53.077 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-16] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:22097]
[testd3]
14:12:53.079 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-15] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
14:12:53.101 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:12:53.106 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-12] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
14:12:53.109 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  Remoting - Starting remoting
14:12:53.120 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-19] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:53.137 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:22130]
[testh3]
14:12:53.143 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-6] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
14:12:53.152 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-13] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:53.181 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-12] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
14:12:53.182 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-19] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
14:12:53.201 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-18] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:53.211 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-12] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
14:12:53.226 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-14] ERROR c.itrsgroup.actor.DataSetClientActor - Exception calling error callback
java.lang.RuntimeException: null
	at geneos_notification.thread_operations.ThreadInstance$2.error(ThreadInstance.java:100) ~[main/:na]
	at com.itrsgroup.actor.ClientActor$$anonfun$1.apply$mcV$sp(ClientActor.scala:143) ~[geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor$$anonfun$1.apply(ClientActor.scala:143) ~[geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor$$anonfun$1.apply(ClientActor.scala:143) ~[geneos-openaccess-client.jar:2.0.1]
	at scala.util.Try$.apply(Try.scala:191) ~[geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor.fireError(ClientActor.scala:143) [geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor$$anonfun$receive$1.applyOrElse(ClientActor.scala:84) [geneos-openaccess-client.jar:2.0.1]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor.aroundReceive(ClientActor.scala:38) [geneos-openaccess-client.jar:2.0.1]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [geneos-openaccess-client.jar:2.0.1]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [geneos-openaccess-client.jar:2.0.1]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [geneos-openaccess-client.jar:2.0.1]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [geneos-openaccess-client.jar:2.0.1]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [geneos-openaccess-client.jar:2.0.1]
]]></system-out>
  <system-err><![CDATA[Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testa2
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testa3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testa3@Default & testa3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testa3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testa3@Default with device testa3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testa3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testa3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testb3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testb3@Default & testb3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testb3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testb3@Default with device testb3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testb3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testc3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testc3@Default & testc3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testc3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testb3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testc3@Default with device testc3
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at geneos_notification.thread_operations.ThreadInstance.run(ThreadInstance.java:105)
	at geneos_notification.thread_operations.ThreadInstance.runScan(ThreadInstance.java:65)
	at geneos_notification.thread_operations.ThreadInstance.startSample(ThreadInstance.java:51)
	at geneos_notification.thread_operations.ThreadInstance.<init>(ThreadInstance.java:42)
	at geneos_notification.controllers.ThreadController$MyAnalysis.callThread(ThreadController.java:124)
	at geneos_notification.controllers.ThreadController$MyAnalysis.call(ThreadController.java:119)
	at geneos_notification.controllers.ThreadController$MyAnalysis.call(ThreadController.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
SEVERE: [T-ERROR]Thread cycle execution failed due to interrupt
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
SEVERE: java.lang.InterruptedException
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at geneos_notification.thread_operations.ThreadInstance.run(ThreadInstance.java:105)
	at geneos_notification.thread_operations.ThreadInstance.runScan(ThreadInstance.java:65)
	at geneos_notification.thread_operations.ThreadInstance.startSample(ThreadInstance.java:51)
	at geneos_notification.thread_operations.ThreadInstance.<init>(ThreadInstance.java:42)
	at geneos_notification.controllers.ThreadController$MyAnalysis.callThread(ThreadController.java:124)
	at geneos_notification.controllers.ThreadController$MyAnalysis.call(ThreadController.java:119)
	at geneos_notification.controllers.ThreadController$MyAnalysis.call(ThreadController.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Thread Execution successful
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testb3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
WARNING: [T-WARNING]OpenAccess null response due to multiple reloads, this is handled and expected.
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testf3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testf3@Default & testf3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testb3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testf3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testf3@Default with device testf3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread terminated : testf3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testi3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testi3@Default & testi3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testi3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testi3@Default with device testi3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testi3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testi3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testi3@Default & testj3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testj3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: testi3@Default logged in successfully on device testj3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testi3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testd3@Default
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testd3@Default & testd3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testd3 logged in successfully
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testd3@Default with device testd3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread terminated : testd3
Feb 11, 2016 2:12:52 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testi3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : teste3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testg3@Default
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testg3@Default & testg3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testg3 logged in successfully
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testg3@Default with device testg3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testg3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Login attempt with username : testh3@Default
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Checking user : testh3@Default & testh3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [SQL]Device testh3 logged in successfully
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : teste3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Initial log on for testh3@Default with device testh3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Thread restarted : testg3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Initialization of thread for xpath : testg3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testg3
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
SEVERE: [T-ERROR]Error retrieving DataSet: java.lang.Exception: Invalid step in path: testa2
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Thread Execution successful
Feb 11, 2016 2:12:53 PM geneos_notification.loggers.LogObject doLog
WARNING: [T-WARNING]OpenAccess null response due to multiple reloads, this is handled and expected.
]]></system-err>
</testsuite>
